---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: athenz-zms-server
  labels:
    app.kubernetes.io/name: athenz-zms-server
    app.kubernetes.io/instance: athenz-zms-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: athenz-zms-server
      app.kubernetes.io/instance: athenz-zms-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: athenz-zms-server
        app.kubernetes.io/instance: athenz-zms-server
    spec:
      restartPolicy: Always
      dnsPolicy: "ClusterFirst"
      volumes:
        - name: athenz-zms-cert-stores
          secret:
            secretName: athenz-zms-cert-stores
            defaultMode: 0555
            items:
              - key: zms_keystore.pkcs12
                path: zms_keystore.pkcs12
              #- key: zms_truststore.jks
              #  path: zms_truststore.jks
              #- key: zms_truststore.pkcs12
              #  path: zms_truststore.pkcs12
        - name: athenz-zms-keys
          secret:
            secretName: athenz-zms-keys
            defaultMode: 0555
            items:
              - key: zms.private.pem
                path: zms.private.pem
        - name: athenz-zms-conf
          configMap:
            name: athenz-zms-conf
        - name: athenz-plugins
          emptyDir: {}
        - name: athenz-trust-store
          emptyDir: {}
        - name: athenz-cacert
          configMap:
            name: athenz-cacert
            items:
              - key: ca.cert.pem
                path: ca-certificates.crt
      initContainers:
        - name: athenz-auth-core
          image: ghcr.io/t4niwa/athenz-auth-core:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAR_DESTINATION
              value: /athenz/plugins/
          resources:
            limits:
              memory: 32Mi
              cpu: 100m
            requests:
              memory: 16Mi
              cpu: 50m
          volumeMounts:
            - name: athenz-plugins
              mountPath: /athenz/plugins
        # TODO: athenz-zms-server-wait should be implemented in athenz-zms-server in future
        - name: athenz-zms-server-wait
          image: ghcr.io/t4niwa/athenz-zms-server:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
          command:
            - sh
            - -c
          args:
            - |
              while true; do nc -vzw3 athenz-db.athenz.svc.cluster.local 3306 && break; done
      containers:
        - name: athenz-zms-server
          image: ghcr.io/t4niwa/athenz-zms-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: ROOT
              value: /opt/athenz/zms
            - name: CLASSPATH
              value: /opt/athenz/zms/lib/jars/*
            - name: CONF_PATH
              value: /opt/athenz/zms/conf/zms_server
            - name: JAVA_OPTS
              value: "-Dathenz.root_dir=/opt/athenz/zms -Dathenz.jetty_home=/opt/athenz/zms -Dathenz.access_log_dir=/opt/athenz/zms/logs"
            - name: USER_CLASSPATH
              value: /usr/lib/jars/*:/athenz/plugins/*
            - name: ZMS_STOP_TIMEOUT
              value: "30"
            - name: ZMS_PRIVATE_KEY
              value: /opt/athenz/zms/var/keys/zms.private.pem
            - name: ZMS_RSA_PRIVATE_KEY
              value: /opt/athenz/zms/var/keys/zms.private.pem
            - name: ZMS_EC_PRIVATE_KEY
              value: /opt/athenz/zms/var/keys/zms.private.pem
            - name: ZMS_PRIVATE_KEY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZMS_RSA_PRIVATE_KEY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZMS_EC_PRIVATE_KEY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZMS_TRUSTSTORE_PEM_PATH
              value: /etc/ssl/certs/ca-certificates.crt
          ports:
            - name: https
              containerPort: 4443
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            exec:
              command:
                - curl
                - -s
                - --fail
                - --resolve
                - athenz-zms-server.athenz:4443:127.0.0.1
                - https://athenz-zms-server.athenz:4443/zms/v1/status
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            exec:
              command:
                - curl
                - -s
                - --fail
                - --resolve
                - athenz-zms-server.athenz:4443:127.0.0.1
                - https://athenz-zms-server.athenz:4443/zms/v1/status
          resources:
            limits:
              memory: 2Gi
              cpu: 2
            requests:
              memory: 100Mi
              cpu: 200m
          volumeMounts:
            - name: athenz-zms-conf
              mountPath: /opt/athenz/zms/conf/zms_server
              readOnly: true
            - name: athenz-zms-keys
              mountPath: /opt/athenz/zms/var/keys
              readOnly: true
            - name: athenz-zms-cert-stores
              mountPath: /opt/athenz/zms/var/certs
              readOnly: true
            - name: athenz-trust-store
              mountPath: /var/run/athenz/truststore
            - name: athenz-plugins
              mountPath: /athenz/plugins
            - name: athenz-cacert
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca-certificates.crt
              readOnly: true
