apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
- deployment.yaml
- namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- files:
  - athenz_admin.cert.pem=certs/athenz_admin.cert.pem
  - athenz_admin.private.pem=keys/athenz_admin.private.pem
  name: athenz-admin-keys
  type: Opaque
images:
- name: ghcr.io/t4niwa/athenz-cli:latest
  newName: ghcr.io/t4niwa/athenz-cli
  newTag: latest
