---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: athenz-db
  labels:
    app.kubernetes.io/name: athenz-db
    app.kubernetes.io/instance: athenz-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: athenz-db
      app.kubernetes.io/instance: athenz-db
  serviceName: athenz-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: athenz-db
        app.kubernetes.io/instance: athenz-db
    spec:
      restartPolicy: Always
      volumes:
        - name: databases
          emptyDir: {}
      containers:
        - name: athenz-db
          image: ghcr.io/t4niwa/athenz-db:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MYSQL_ROOT_PASSWORD
              value: ""
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3306
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
          volumeMounts:
            - name: databases
              mountPath: /config/databases/
