apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
- deployment.yaml
- namespace.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- files:
  - ui.private.pem=keys/ui.private.pem
  - ui.public.pem=keys/ui.public.pem
  - ui.cert.pem=certs/ui.cert.pem
  name: athenz-ui-keys
  type: Opaque
- files:
  - athenz_admin.private.pem=keys/athenz_admin.private.pem
  - athenz_admin.cert.pem=certs/athenz_admin.cert.pem
  name: athenz-admin-keys
  type: Opaque

configMapGenerator:
- files:
  - extended-config.js=config/extended-config.js
  name: athenz-ui-config
images:
- name: ghcr.io/t4niwa/athenz-ui:latest
  newName: ghcr.io/t4niwa/athenz-ui
  newTag: latest
